version: '3.8'

services:
  shopapp-backend:
#    image: shopapp-backend-v0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shopapp-backend
    depends_on:
      - mysql8-container
    restart: always
    ports:
      - "8888:8888"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql8-container:3306/ShopApp?autoReconnect=true&useSSL=false&serverTimezone=UTC
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345678@@
      MYSQL_PORT: 3306
    networks:
      - shopapp-network

  mysql8-container:
    image: mysql:8.2.0
    container_name: mysql8-container
    restart: always
    ports:
      - 3307:3306
    networks:
      - shopapp-network
    environment:
      MYSQL_ROOT_PASSWORD: 12345678@@
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: shopapp
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql_dump:/docker-entrypoint-initdb.d

  phpmyadmin8-container:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin8-container
    restart: always
    ports:
      - "8088:80"
    depends_on:
      - mysql8-container
    environment:
      PMA_HOST: mysql8-container
    networks:
      - shopapp-network

networks:
  shopapp-network:
    name: shopapp-network
    driver: bridge

volumes:
  mysql_data:
    driver: local