server:
  port: 8888
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgres://shopapp_backend_01:8FHZUeJvebZdV8IPEaagsF7ZwcCddCIq@dpg-cpjvru821fec73a54gvg-a.singapore-postgres.render.com/shopapp_backend_01?useSSL=false&serverTimezone=UTC}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: shopapp_backend_01
    password: ${MYSQL_ROOT_PASSWORD:8FHZUeJvebZdV8IPEaagsF7ZwcCddCIq}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en
api:
  prefix: api/v1
jwt:
  expiration: 2592000 #30 days
  secretKey: qQXx+PWzVj+0VUysdiTARsG7FQ5I2nSODQ27XO4eJF8=
